### ISSUE TITLE
Deeplabcut crashes automatically after updating to 2.3.0

### ISSUE THREAD

**Issue by VenkateshLab** [DeepLabCut/DeepLabCut#2142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I recently updated to DLC 2.3.0. after updating it.  after labbeling the frames using napari after saving the point. it getting crached. i tried the same thing in different platform the same issue happened in mac os, ubuntu 20.04 and in windows. do i need to downgrade anything to fix this issue. 

```
(DEEPLABCUT_M1) ➜  alma pythonw -m deeplabcut
Loading DLC 2.3.0...
Starting GUI...
618it [00:08, 75.01it/s]
/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
2023-02-03 12:36:10.297 python[29893:16984792] +[CATransaction synchronize] called within transaction
WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget
Traceback (most recent call last):
  File "shibokensupport/signature/mapping.py", line 196, in update
  File "shibokensupport/signature/mapping.py", line 197, in <genexpr>
  File "shibokensupport/signature/mapping.py", line 182, in module_valid
AttributeError: 'CythonDotParallel' object has no attribute '__name__'
Fatal Python error: seterror_argument failed to call update_mapping
Python runtime state: initialized

Thread 0x00000002f66b3000 (most recent call first):
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/concurrent/futures/thread.py", line 81 in _worker
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 917 in run
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x000000017e25f000 (most recent call first):
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 316 in wait
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 581 in wait
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tqdm/_monitor.py", line 60 in run
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00000002bcfcb000 (most recent call first):
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/threading.py", line 312 in wait
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/queue.py", line 171 in get
  File "/Users/manojkumark/Desktop/DLC/DeepLabCut/deeplabcut/gui/widgets.py", line 206 in run

Current thread 0x00000001f4656500 (most recent call first):
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 617 in _save_layers_dialog
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/_qt/menus/file_menu.py", line 82 in <lambda>
  File "/Users/manojkumark/Desktop/DLC/DeepLabCut/deeplabcut/gui/launch_script.py", line 69 in launch_dlc
  File "/Users/manojkumark/Desktop/DLC/DeepLabCut/deeplabcut/__main__.py", line 24 in <module>
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/runpy.py", line 87 in _run_code
  File "/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/runpy.py", line 197 in _run_module_as_main
*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
0   libtensorflow_framework.2.dylib     0x0000000104519dc8 _ZN3tsl7testingL17StacktraceHandlerEiP9__siginfoPv + 160
1   libsystem_platform.dylib            0x0000000198fc02a4 _sigtramp + 56
2   libsystem_pthread.dylib             0x0000000198f91cec pthread_kill + 288
3   libsystem_c.dylib                   0x0000000198ecb2c8 abort + 180
4   python3.9                           0x0000000100261e84 fatal_error_exit + 16
5   python3.9                           0x0000000100261bc8 fatal_error + 608
6   python3.9                           0x0000000100261e74 fatal_error_exit + 0
7   libshiboken6.abi3.6.3.dylib         0x000000016cc85af4 SetError_Argument + 904
8   QtWidgets.abi3.so                   0x0000000294a4b76c _ZL35Sbk_QFileDialogFunc_getSaveFileNameP7_objectS0_S0_ + 168
9   python3.9                           0x000000010017c428 cfunction_call + 80
10  python3.9                           0x000000010012d3f4 _PyObject_MakeTpCall + 616
11  python3.9                           0x000000010021d494 call_function + 668
12  python3.9                           0x0000000100219cf4 _PyEval_EvalFrameDefault + 26580
13  python3.9                           0x0000000100212ec8 _PyEval_EvalCode + 2804
14  python3.9                           0x000000010012e014 _PyFunction_Vectorcall + 220
15  python3.9                           0x0000000100130df4 method_vectorcall + 164
16  python3.9                           0x000000010021d3fc call_function + 516
17  python3.9                           0x0000000100219cf4 _PyEval_EvalFrameDefault + 26580
18  python3.9                           0x0000000100212ec8 _PyEval_EvalCode + 2804
19  python3.9                           0x000000010012e014 _PyFunction_Vectorcall + 220
20  libpyside6.abi3.6.3.dylib           0x000000016cf336c0 _ZN6PySide13SignalManager20callPythonMetaMethodERK11QMetaMethodPPvP7_objectb + 532
21  libpyside6.abi3.6.3.dylib           0x000000016cf36348 _ZN6PySide16GlobalReceiverV211qt_metacallEN11QMetaObject4CallEiPPv + 740
22  QtCore                              0x0000000173f55c34 _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3020
23  QtGui                               0x00000001755b4e5c _ZN7QAction8activateENS_11ActionEventE + 368
24  QtCore                              0x0000000173f4ebcc _ZN7QObject5eventEP6QEvent + 584
25  QtWidgets                           0x000000028e0b61c8 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 272
26  QtWidgets                           0x000000028e0b7230 _ZN12QApplication6notifyEP7QObjectP6QEvent + 512
27  QtCore                              0x0000000173f0d6a0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 208
28  QtCore                              0x0000000173f0e8e4 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData + 808
29  libqcocoa.dylib                     0x000000029903cc88 qt_plugin_instance + 54492
30  libqcocoa.dylib                     0x000000029903d318 qt_plugin_instance + 56172
31  CoreFoundation                      0x0000000199071a34 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
32  CoreFoundation                      0x00000001990719c8 __CFRunLoopDoSource0 + 176
33  CoreFoundation                      0x0000000199071738 __CFRunLoopDoSources0 + 244
34  CoreFoundation                      0x000000019907033c __CFRunLoopRun + 836
35  CoreFoundation                      0x000000019906f8a4 CFRunLoopRunSpecific + 612
36  HIToolbox                           0x00000001a26e33bc RunCurrentEventLoopInMode + 292
37  HIToolbox                           0x00000001a26e304c ReceiveNextEventCommon + 236
38  HIToolbox                           0x00000001a26e2f48 _BlockUntilNextEventMatchingListInModeWithFilter + 72
39  AppKit                              0x000000019c2c8630 _DPSNextEvent + 632
40  AppKit                              0x000000019c2c77c0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
41  AppKit                              0x000000019c2bbbf0 -[NSApplication run] + 464
42  libqcocoa.dylib                     0x000000029903c200 qt_plugin_instance + 51796
43  QtCore                              0x0000000173f16cfc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 544
44  QtCore                              0x0000000173f0dd54 _ZN16QCoreApplication4execEv + 128
45  QtWidgets.abi3.so                   0x00000002949891b4 _ZL26Sbk_QApplicationFunc_exec_P7_object + 176
46  python3.9                           0x000000010017cf78 cfunction_vectorcall_NOARGS + 264
47  python3.9                           0x000000010021d3fc call_function + 516
48  python3.9                           0x0000000100219bfc _PyEval_EvalFrameDefault + 26332
49  python3.9                           0x000000010012e0d0 function_code_fastcall + 116
50  python3.9                           0x000000010021d3fc call_function + 516
51  python3.9                           0x0000000100219c78 _PyEval_EvalFrameDefault + 26456
52  python3.9                           0x0000000100212ec8 _PyEval_EvalCode + 2804
53  python3.9                           0x00000001002123c8 PyEval_EvalCode + 76
54  python3.9                           0x000000010020df70 builtin_exec + 844
55  python3.9                           0x000000010017d1c8 cfunction_vectorcall_FASTCALL + 216
56  python3.9                           0x000000010021d3fc call_function + 516
57  python3.9                           0x0000000100219c78 _PyEval_EvalFrameDefault + 26456
58  python3.9                           0x0000000100212ec8 _PyEval_EvalCode + 2804
59  python3.9                           0x000000010012e014 _PyFunction_Vectorcall + 220
60  python3.9                           0x000000010021d3fc call_function + 516
61  python3.9                           0x0000000100219c78 _PyEval_EvalFrameDefault + 26456
62  python3.9                           0x0000000100212ec8 _PyEval_EvalCode + 2804
63  python3.9                           0x000000010012e014 _PyFunction_Vectorcall + 220
64  python3.9                           0x000000010028cf68 pymain_run_module + 272
65  python3.9                           0x000000010028c6a8 Py_RunMain + 1612
66  python3.9                           0x000000010028da40 pymain_main + 1252
67  python3.9                           0x00000001000e07a0 main + 56
68  dyld                                0x0000000198c67e50 start + 2544
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
	tsl::CurrentStackTrace()
	tsl::testing::StacktraceHandler(int, __siginfo*, void*)
	_sigtramp
	pthread_kill
	abort
	fatal_error_exit
	fatal_error
	fatal_error_exit
	SetError_Argument
	Sbk_QFileDialogFunc_getSaveFileName(_object*, _object*, _object*)
	cfunction_call
	_PyObject_MakeTpCall
	call_function
	_PyEval_EvalFrameDefault
	_PyEval_EvalCode
	_PyFunction_Vectorcall
	method_vectorcall
	call_function
	_PyEval_EvalFrameDefault
	_PyEval_EvalCode
	_PyFunction_Vectorcall
	PySide::SignalManager::callPythonMetaMethod(QMetaMethod const&, void**, _object*, bool)
	PySide::GlobalReceiverV2::qt_metacall(QMetaObject::Call, int, void**)
	QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
	QAction::activate(QAction::ActionEvent)
	QObject::event(QEvent*)
	QApplicationPrivate::notify_helper(QObject*, QEvent*)
	QApplication::notify(QObject*, QEvent*)
	QCoreApplication::notifyInternal2(QObject*, QEvent*)
	QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
	qt_plugin_instance
	qt_plugin_instance
	__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	__CFRunLoopDoSource0
	__CFRunLoopDoSources0
	__CFRunLoopRun
	CFRunLoopRunSpecific
	RunCurrentEventLoopInMode
	ReceiveNextEventCommon
	_BlockUntilNextEventMatchingListInModeWithFilter
	_DPSNextEvent
	-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
	-[NSApplication run]
	qt_plugin_instance
	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
	QCoreApplication::exec()
	Sbk_QApplicationFunc_exec_(_object*)
	cfunction_vectorcall_NOARGS
	call_function
	_PyEval_EvalFrameDefault
	function_code_fastcall
	call_function
	_PyEval_EvalFrameDefault
	_PyEval_EvalCode
	PyEval_EvalCode
	builtin_exec
	cfunction_vectorcall_FASTCALL
	call_function
	_PyEval_EvalFrameDefault
	_PyEval_EvalCode
	_PyFunction_Vectorcall
	call_function
	_PyEval_EvalFrameDefault
	_PyEval_EvalCode
	_PyFunction_Vectorcall
	pymain_run_module
	Py_RunMain
	pymain_main
	main
	start
*** End stack trace ***
/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/bin/pythonw: line 3: 29893 Abort trap: 6           /Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/python.app/Contents/MacOS/python "$@"
/Users/manojkumark/miniconda/envs/DEEPLABCUT_M1/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Operating System

operating system : Mac os , Windows and ubuntu 

### DeepLabCut version

dlc version : 2.3.0

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
It looks like the crash is caused by `shibokensupport`. I checked all my DLC environments and could not find it, so I assume it should be safe to delete. You could use `conda list` to get a list of all installed packages: if you see `shibokensupport` or `shiboken2` or `shiboken6`, uninstall it with `pip uninstall shiboken6` for example.

**Comment by natsukium** [comment]
The new GUI framework PySide6 depends on `shiboken6` so you cannot uninstall it.
It seems to be a problem between shiboken and cython.parallel, but I can't find a similar case and don't know how to solve it.

**Comment by raul-silva** [comment]
I'm having the very same problem running on Windows 11 (I did not try other platforms as @natsukium). But up to now, all I could do to overcome the problem is downgrade to version 2.2.3.

**Comment by backyardbiomech** [comment]
I run DLC==2.3.0 on Windows 10 without a hitch with the setup below.
<details>

```

absl-py                   1.4.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
ansicon                   1.89.0                   pypi_0    pypi
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
app-model                 0.1.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h91455d4_3    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.2.0             pyh71513ae_0    conda-forge
babel                     2.11.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blessed                   1.19.1                   pypi_0    pypi
blosc2                    2.0.0                    pypi_0    pypi
build                     0.10.0                   pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.01.10           haa95532_0
cachetools                5.2.1                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1           py38h57701bc_3    conda-forge
charset-normalizer        3.0.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cudatoolkit               11.8.0              h09e9e62_11    conda-forge
cudnn                     8.4.1.50             hf5f08ae_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
dask                      2023.1.0                 pypi_0    pypi
dask-image                2022.9.0                 pypi_0    pypi
debugpy                   1.6.5            py38hd3f51b4_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deeplabcut                2.3.0                     dev_0    <develop>
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dlc2kinematics            0.0.4                    pypi_0    pypi
dlclibrary                0.0.2                    pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h1537add_0    conda-forge
ffmpeg                    5.1.2           gpl_h5b1d025_105    conda-forge
filelock                  3.9.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               23.1.4                   pypi_0    pypi
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h546665d_1    conda-forge
freetype-py               2.3.0                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
google-auth               2.16.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
gst-plugins-base          1.21.3               h001b923_1    conda-forge
gstreamer                 1.21.3               h6b5321d_1    conda-forge
h5py                      3.7.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
huggingface-hub           0.11.1                   pypi_0    pypi
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.24.0                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_resources       5.10.2             pyhd8ed1ab_0    conda-forge
in-n-out                  0.1.6                    pypi_0    pypi
intel-openmp              2022.2.1                 pypi_0    pypi
ipykernel                 6.20.2             pyh025b116_0    conda-forge
ipython                   8.8.0              pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.4              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinxed                    1.2.0                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38haa244fe_8    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.3            py38haa244fe_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.1.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.5              pyhd8ed1ab_0    conda-forge
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               heb0366b_0    conda-forge
libclang                  15.0.6.1                 pypi_0    pypi
libclang13                15.0.7          default_h77d9078_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzlib-wapi              1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
magicgui                  0.6.1                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.1.0                    pypi_0    pypi
markupsafe                2.1.2            py38h91455d4_0    conda-forge
matplotlib                3.6.3                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mpmath                    1.2.1                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
napari                    0.4.17rc8                pypi_0    pypi
napari-console            0.0.7                    pypi_0    pypi
napari-deeplabcut         0.1.1.dev3+g5a5709d          pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
nb_conda                  2.2.1                     win_6    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_2    conda-forge
nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.8              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.8              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.8              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.0                      pypi_0    pypi
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
npe2                      0.6.2                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numexpr                   2.8.4                    pypi_0    pypi
numpy                     1.21.0                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.68                 pypi_0    pypi
opencv-python-headless    4.7.0.68                 pypi_0    pypi
openh264                  2.3.1                h63175ca_1    conda-forge
openssl                   3.0.7                hcfcfb64_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3                    pypi_0    pypi
pandoc                    2.19.2               h57928b3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pint                      0.20.1                   pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.2              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.15.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
prompt_toolkit            3.0.36               hd8ed1ab_0    conda-forge
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.4            py38h91455d4_0    conda-forge
psygnal                   0.7.0                    pypi_0    pypi
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.4                   pypi_0    pypi
pygame                    2.1.2                    pypi_0    pypi
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.8                    pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyproject-hooks           1.0.0                    pypi_0    pypi
pyqt                      5.15.7           py38hd6c051e_2    conda-forge
pyqt5-sip                 12.11.0          py38hd3f51b4_2    conda-forge
pyrsistent                0.19.3           py38h91455d4_0    conda-forge
pyside6                   6.3.1                    pypi_0    pypi
pyside6-addons            6.3.1                    pypi_0    pypi
pyside6-essentials        6.3.1                    pypi_0    pypi
python                    3.8.15          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.4              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytomlpp                  1.0.11                   pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   304              py38hd3f51b4_2    conda-forge
pywinpty                  2.0.10           py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h91455d4_5    conda-forge
pyzmq                     25.0.0           py38ha85f68a_0    conda-forge
qdarkstyle                3.1                      pypi_0    pypi
qt-main                   5.15.6               h9580fe5_5    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.2.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-kinematics         0.8.8                    pypi_0    pypi
scikit-learn              1.2.0                    pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                66.1.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.0                    pypi_0    pypi
shiboken6                 6.3.1                    pypi_0    pypi
sip                       6.7.5            py38hd3f51b4_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.1.0                    pypi_0    pypi
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.3                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5                   pypi_0    pypi
superqt                   0.4.1                    pypi_0    pypi
svt-av1                   1.4.1                h63175ca_0    conda-forge
sympy                     1.11.1                   pypi_0    pypi
tables                    3.8.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.29.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
terminado                 0.17.0             pyh08f2357_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.10.10               pypi_0    pypi
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
tornado                   6.2              py38h91455d4_1    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.8.1              pyhd8ed1ab_0    conda-forge
typer                     0.7.0                    pypi_0    pypi
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
umap-learn                0.5.3                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vg                        2.0.0                    pypi_0    pypi
vispy                     0.11.0                   pypi_0    pypi
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.2              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.5              pyhd8ed1ab_0    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```
</details>

**Comment by natsukium** [comment]
OK, I found that this error is caused by clicking "Save All Layers".
I'm unfamiliar with 'napari' so I don't know what layers are. However, I select "Save Selected Layer(s)..." and can save the labeled data without crashing on one of my environments, Windows 11 and conda.
