### ISSUE TITLE
TypeError: analyze_videos() got an unexpected keyword argument 'cropping'

### ISSUE THREAD

**Issue by sansanai** [DeepLabCut/DeepLabCut#728]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Ubuntu 18.04
DeepLabCut Version: 2.1.8.2
Anaconda env used: yes (python 3.7.7 tf-gpu 1.13.1

**Describe the problem**
I followed video tutorial for DeepLabCut Installation How To : testing your DLC installation w/testscript.py.
I run 'python testscript.py' in examples directory.
But I got an error ...

Please place code inside this:

<details><summary>Code output</summary><p>

video:189kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.139685%
Inference with direct cropping
Traceback (most recent call last):
  File "testscript.py", line 299, in <module>
    cropping=[0, 50, 0, 50],
TypeError: analyze_videos() got an unexpected keyword argument 'cropping'

</p></details>

**How to Reproduce the problem**
1. Go to 'examples directory'
2. Type  'python testscript.py'
3. See error

**Comment by hugofluhr** [comment]
It looks to me like the test_scipt.py that you are using is meant to be used with DLC 2.2 since the parameters of `deeplacut.analyze_videos` have changed with this new release (cropping insteand of crop). 
You should maybe try to run a previous version of the script so that it works with 2.1.x.

**Comment by jeylau** [comment]
Hi @sansanai! @hugofluhr is right, the 'cropping' keyword appeared recently. What puzzles me though is that the testscript runs smoothly in 2.1.8.2 (it has the right argument...and only 223 lines).

**Comment by sansanai** [comment]
Hi @hugofluhr, 
I'am a new to DeepLabCut toolbox.
Could you tell me how to get  previous version of the 'testscript.py' script so that it works with 2.1.x?
And I have one question. I followed installation guide from https://github.com/DeepLabCut/DeepLabCut. but I have a  version DLC 2.1.8.2 not DLC 2.2. How to upgrade DLC from 2.1.8.2 to DLC 2.2?

**Comment by jeylau** [comment]
Please run `pip install deeplabcut==2.2b6`.

**Comment by sansanai** [comment]
Hi @jeylau,

I uninstalled previouse deeplabcut 2.1.8.2. and installed DLC v2.2b6.
I ran 'python testscript.py' and there was no error.
Thank you.
