### ISSUE TITLE
after upgrading deeplabcut from 2.1.8 to 2.2.0.3, it can't be used

### ISSUE THREAD

**Issue by Vergil98** [DeepLabCut/DeepLabCut#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

before upgrading, Deeplabcut 2.1.8 can work.
But after upgrading, I can't launch Deeplabcut 2.2.0.3 GUI, and it reports"AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'
However, I find the File "pose_estimation_tensorflow" in the anaconda environments file.
So I don't know how to eliminate this error

<img width="766" alt="微信图片_20211231073224" src="https://user-images.githubusercontent.com/96836398/147794421-e325624f-0669-4a0b-8658-5a0295c15528.png">
.

### Operating System

Window 11

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

single animal

### Device type

GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Vergil98** [comment]
I upgrade the deeplabcut with "pip install --upgrade deeplabcut"
and tensorflow version is 1.13.1,   python version is 3.6.13
<img width="720" alt="image" src="https://user-images.githubusercontent.com/96836398/147794859-f399d173-b25d-46d6-9a25-ef8027e30c7b.png">

Traceback (most recent call last):
    import deeplabcut
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 15, in <module>
    from deeplabcut.pose_estimation_tensorflow.core.train import *
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 29, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnets import PoseNetFactory
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\__init__.py", line 15, in <module>
    from .efficientnet import PoseEfficientNet
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\efficientnet.py", line 20, in <module>
    import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_builder as eff
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\backbones\efficientnet_builder.py", line 20, in <module>
    import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_model as efficientnet_model
  File "C:\Users\Vergil\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\backbones\efficientnet_model.py", line 25, in <module>
    import deeplabcut.pose_estimation_tensorflow.nnets.utils as utils
AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'
