### ISSUE TITLE
Labeling GUI not working (if config path is incorrect, GUI will not function correctly)

### ISSUE THREAD

**Issue by Umar-Ayub** [DeepLabCut/DeepLabCut#97]
**OS and version**
Windows 10, DLC2.0

**Describe the problem**
The labeling GUI isn't working properly when I press the LabelFrame button and select the directory, the notebook dies. Following is a traceback:

 FileNotFoundError                         Traceback (most recent call last)
D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\DeepLabCut\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    139             self.Close(True)
    140         dlg.Destroy()
--> 141         with open(str(self.config_file), 'r') as ymlfile:
    142             self.cfg = yaml.load(ymlfile)
    143         self.scorer = self.cfg['scorer']

FileNotFoundError: [Errno 2] No such file or directory: 'Digits\\Digits-Umar-2018-11-07\\config.yaml'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\DeepLabCut\deeplabcut\generate_training_dataset\labeling_toolbox.py in nextImage(self, event)
    219         from skimage import io
    220         self.file = 1
--> 221         MainFrame.saveEachImage(self)
    222         self.canvas.Destroy()
    223         plt.close(self.fig1)

D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\DeepLabCut\deeplabcut\generate_training_dataset\labeling_toolbox.py in saveEachImage(self)
    253         Saves data for each image
    254         """
--> 255         plt.close(self.fig1)
    256 
    257         for idx, bp in enumerate(self.updatedCoords):

AttributeError: 'MainFrame' object has no attribute 'fig1'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\DeepLabCut\deeplabcut\generate_training_dataset\labeling_toolbox.py in nextImage(self, event)
    219         from skimage import io
    220         self.file = 1
--> 221         MainFrame.saveEachImage(self)
    222         self.canvas.Destroy()
    223         plt.close(self.fig1)

D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\DeepLabCut\deeplabcut\generate_training_dataset\labeling_toolbox.py in saveEachImage(self)
    253         Saves data for each image
    254         """
--> 255         plt.close(self.fig1)
    256 
    257         for idx, bp in enumerate(self.updatedCoords):

AttributeError: 'MainFrame' object has no attribute 'fig1'

ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000002B09E945C80>)
Traceback (most recent call last):
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\dlc2\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\dlc2\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\dlc2\lib\site-packages\ipykernel\kernelbase.py", line 306, in advance_eventloop
    eventloop(self)
  File "C:\Users\ua12\AppData\Local\conda\conda\envs\dlc2\lib\site-packages\ipykernel\eventloops.py", line 238, in loop_tk
    app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'

**Other Information**
Don't know exactly why the gui isn't working but the images aren't loading.

** Additional **
Is there backwards compatibility with version 1? I have lots of labelled data and would just like to use that instead of relabeling. Was mainly interested in the relabeling feature during incorrect training.

**Comment by MMathisLab** [comment]
it is bad practice to have spaces and characters like ``(`` in file names. i.e. `` D:\New folder\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 11-5\ `` that might be causing the issues as others have it working fine in Windows10... 

Looks like your first error states: **"FileNotFoundError: [Errno 2] No such file or directory: 'Digits\Digits-Umar-2018-11-07\config.yaml'"** So the config file was not found... Is the config.yaml file in the folder that it's looking for? 

It is backwards compatible - there will be code to convert from DLC1 -> 2 at https://github.com/AlexEMG/DLCutils (as stated in the README: Nov 2018: Various (post-hoc) analysis scripts contributed by users (and us) will be gathered at DLCutils. Feel free to contribute! In particular, there is a script guiding you through importing a project into the new data format for DLC 2.0)

**Comment by MMathisLab** [comment]
Looks like your first error states: "FileNotFoundError: [Errno 2] No such file or directory: 'Digits\Digits-Umar-2018-11-07\config.yaml'" So the config file was not found?

**Comment by AlexEMG** [comment]
** Additional **
Is there backwards compatibility with version 1? I have lots of labelled data and would just like to use that instead of relabeling. Was mainly interested in the relabeling feature during incorrect training.

Yes, it is backward compatible. We will add a script to import "old" projects to DLC2  tomorrow...

**Comment by Umar-Ayub** [comment]
Yes the problem was in the path. I didn't concatenate the base path with the local path. Thanks!
