### ISSUE TITLE
after upgrade to v2.2, can't import deeplabcut 

### ISSUE THREAD

**Issue by asafbenj** [DeepLabCut/DeepLabCut#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Had a working version of deeplabcut (v1.9). After upgrading to v2.2, running `import deeplabcut` raises error

```
2022-09-08 16:21:22.297155: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-08 16:21:22.304440: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
...
AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'
```

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.0.6

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

start anaconda prompt
conda activate dlc-windowsGPU
pip install --upgrade deeplabcut
ipython
import deeplabcut

### Relevant log output

```shell
2022-09-08 16:21:22.297155: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-08 16:21:22.304440: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\__init__.py in <module>
     25
     26     mpl.use("WxAgg")
---> 27     from deeplabcut import generate_training_dataset
     28     from deeplabcut import refine_training_dataset
     29

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py in <module>
     10
     11 from deeplabcut.generate_training_dataset.frame_extraction import *
---> 12 from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
     13 from deeplabcut.generate_training_dataset.multiple_individuals_trainingsetmanipulation import *

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in <module>
     22 import yaml
     23
---> 24 from deeplabcut.pose_estimation_tensorflow import training
     25 from deeplabcut.utils import (
     26     auxiliaryfunctions,

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py in <module>
     13 from deeplabcut.pose_estimation_tensorflow.default_config import *
     14 from deeplabcut.pose_estimation_tensorflow.core.evaluate import *
---> 15 from deeplabcut.pose_estimation_tensorflow.core.train import *
     16 from deeplabcut.pose_estimation_tensorflow.core.test import *
     17 from deeplabcut.pose_estimation_tensorflow.export import export_model

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py in <module>
     28     PoseDatasetFactory,
     29 )
---> 30 from deeplabcut.pose_estimation_tensorflow.nnets import PoseNetFactory
     31 from deeplabcut.pose_estimation_tensorflow.util.logging import setup_logging
     32

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\__init__.py in <module>
     13 """
     14 from .factory import PoseNetFactory
---> 15 from .efficientnet import PoseEfficientNet
     16 from .mobilenet import PoseMobileNet
     17 from .multi import PoseMultiNet

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\efficientnet.py in <module>
     18
     19 import tensorflow as tf
---> 20 import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_builder as eff
     21 from .base import BasePoseNet
     22 from .factory import PoseNetFactory

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\backbones\efficientnet_builder.py in <module>
     18 import tensorflow as tf
     19
---> 20 import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_model as efficientnet_model
     21 import deeplabcut.pose_estimation_tensorflow.nnets.utils as utils
     22

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\backbones\efficientnet_model.py in <module>
     23 import tensorflow as tf
     24
---> 25 import deeplabcut.pose_estimation_tensorflow.nnets.utils as utils
     26
     27 GlobalParams = collections.namedtuple(

AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @asafbenj, it looks like something is wrong with your environment. I'd encourage you to create a new one using the conda `yaml` file we provide in `deeplabcut/conda-environments`. A lot has changed since v1.9, especially the packages we depend on (tensorflow notably), and it is a good idea to not only update deeplabcut, but also to make sure that CUDA libraries are pulled by conda.
