### PR TITLE
Fix fliplr augmentation for multi animal 2

### PR DESCRIPTION
**Pull request by biol-jsh**
The current implementation of fliplr breaks when keypoints are hidden since only labels for visible points are forwarded to the pipeline. This is the second attempt at fixing this as an earlier attempt failed due to the error fixed in PR #2037.

### CODE REVIEW

**Comment by MMathisLab** [comment]
Hi @n-poulsen the tests are failing, can you look into it? `FAILED tests/test_pose_multianimal_imgaug.py::test_get_targetmaps[3] - TypeError: get_targetmaps_update() missing 1 required positional argument: 'scale'`

**Comment by jeylau** [comment]
I'm still having some tests failing when training with identity; I'll push a fix as soon as I find why.

**Comment by jeylau** [comment]
Ready to merge @MMathisLab @n-poulsen

**Comment by MMathisLab** [comment]
Thanks @jeylau - can we get some # on performance? It won't be a default setting, right? But there are docs for it somewhere? :)

**Review by n-poulsen — COMMENTED** [review]
Looks good to me!

**Review by MMathisLab — APPROVED** [review]
