### ISSUE TITLE
 module 'deeplabcut' has no attribute 'train_network'

### ISSUE THREAD

**Issue by leiyaohui** [DeepLabCut/DeepLabCut#278]
hello！The following error occurred when I ran demo.py

import deeplabcut
task='rong1'
experimenter='hhui'
video='F:\DeepLabCut-master\examples\\reachingvideo1.avi'
path_config_file=deeplabcut.create_new_project(task,experimenter,video, working_directory='F:\DeepLabCut-master\examples',copy_videos=True)
deeplabcut.extract_frames(path_config_file,'automyatic','uniform',crop=True)
deeplabcut.label_frames(path_config_file)
deeplabcut.check_labels(path_config_file)
deeplabcut.create_training_dataset(path_config_file)
deeplabcut.train_network(path_config_file)
deeplabcut.evaluate_network(path_config_file)
videofile_path ='F:\DeepLabCut-master\examples\\reachingvideo1.avi'
deeplabcut.analyze_videos(path_config_file,videofile_path)
deeplabcut.create_labeled_video(path_config_file,videofile_path)
deeplabcut.plot_trajectories(path_config_file,videofile_path)

Traceback (most recent call last):
  File "F:/DeepLabCut-master/demo_objdata.py", line 10, in <module>
    deeplabcut.train_network(path_config_file)
AttributeError: module 'deeplabcut' has no attribute 'train_network'
But I can find this script in training.py，And there are a lot of similar operations that can't be imported later.
I look forward to your reply!thanks!

**Comment by FedeClaudi** [comment]
Hi, 

I am also getting the same error after updating deeplabcut to 2.0.6.1:

```
import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Federico\AppData\Local\conda\conda\envs\behav\lib\site-packages\deeplabcut\__init__.py", line 54, in <module>
    from deeplabcut.pose_estimation_tensorflow import train_network, train_network_path
ImportError: cannot import name 'train_network_path'
```

edit: just checked and with version 2.0.5 I didn't have this error. 

Thank you, 
Federico

**Comment by MMathisLab** [comment]
^ different error, but yes - can you roll back to 2.0.6 -will fix today. It’s just an erroneous line in the int.py file!   https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/__init__.py 

https://github.com/AlexEMG/DeepLabCut/issues/276#issuecomment-489380533 

Sorry about that!

**Comment by MMathisLab** [comment]
@leiyaohui can you please fill out the issue template completely, otherwise it is difficult to help

**Comment by AlexEMG** [comment]
Ok, it's on pypi.

pip install deeplabcut==2.0.6.2

**Comment by MMathisLab** [comment]
Not sure the error of original poster is related to “train_network” or “train_network_path” 

- also original poster has an error in code, be sure to fix  the  spelling of automatic: deeplabcut.extract_frames(path_config_file,'automyatic','uniform',crop=True)

**Comment by leiyaohui** [comment]
Thank you for your reply. Now it's working. Thank you again.
