### ISSUE TITLE
Cannot open GUI after updating to 2.3

### ISSUE THREAD

**Issue by thetalker101** [DeepLabCut/DeepLabCut#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Updated to dlc 2.3, got the following error when importing in ipython
```
C:\Users\anaconda3\lib\site-packages\qtpy\__init__.py:267: RuntimeWarning: Selected binding "pyside6" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```
now it says the following when trying to run the GUI
`AttributeError: module 'deeplabcut' has no attribute 'launch_dlc'`
tried to do `set DLClight=` but nothing changed. I also set to true and false, but no change either.
uninstalled and reinstalled dlc, no change.
I am using my Nvidia gpu for cuda processing and other bug reports seem to say there are issues for cuda users.
It used to work on version 2.2.3 .

### Operating System

Windows

### DeepLabCut version

2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

https://github.com/DeepLabCut/DeepLabCut/issues/355
This issue is similar but the command given for windows users did nothing to fix it.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @thetalker101, was deeplabcut installed with the `gui` flag: `pip install deeplabcut[gui]`?

**Comment by thetalker101** [comment]
Thanks for helping me @jeylau , I did that and got the following error:
```
qt.core.plugin.loader: In C:/User/anaconda3/Library/plugins/platforms/qdirect2d.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/User/anaconda3/Library/plugins/platforms/qminimal.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/User/anaconda3/Library/plugins/platforms/qoffscreen.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/User/anaconda3/Library/plugins/platforms/qwebgl.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In C:/User/anaconda3/Library/plugins/platforms/qwindows.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
I reinstalled as it recommended doing `pip uninstall deeplabcut[gui]` and then `pip install deeplabcut[gui]` but nothing changed.
I looked at other threads that looked exactly like this error, it said I may be using the wrong Qt library, so I guess I need to install the right Qt library, but I don't know the commands for that.

**Comment by thetalker101** [comment]
After a lot of experimenting with different versions of the Qt library, I found no version that would work properly. I've decided it would be best just to revert to 2.2.3 and call it at that as I have work to do. I still consider this a working problem, but I will have to ignore it for now.

**Comment by jeylau** [comment]
@thetalker101, what if you tried `pip install "PySide6<6.3.2"`; would you still get the error?

**Comment by thetalker101** [comment]
@jeylau This did not work and the error did not change. Major apologies for not responding sooner as I was caught up in a project related to this application.
